modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="dmich9smod"
version="${file.jarVersion}"
displayName="dmich9's Mod"
logoFile="examplemod.png"
credits="Thanks for this example mod goes to Java"
authors="Dylan Michaud"
description='''
dmich9's Test Mod
'''
[[dependencies.dmich9smod]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dmich9smod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"